### ISSUE TITLE
Add CSS for the Meeting Minutes:

### ISSUE THREAD

**Issue by azpi-arte** [azpi-arte/sp24-cse110-lab3#1]
**Task:** 
## Add specified CSS elements to HTML. 
 - [] add Simple elements like color, display, and psuedo class
 - [] use flexbox and grid
 - [] use class selectors
---
### Use/Add these Simple CSS Elements:
 * Comment
 * Color in rgb, rgba, #FFF, #FFFFFF, hsl, hsla, color name
 * Wide Gamut Color: color(colorspace c1 c2 c3[ / A]),  color-mix(method, color1[ p1], color2[ p2])   
 * CSS variables, CSS variable with a fallback
 * Background 
 * Unit: 3 unique relative units total, 3 unique absolute units total
 * Box model:
    * Borders: border-style, border-color, border-width, border-radius
    * Margin: Long, Short, Auto margins
    * Padding: Long, Short
 * Text: color, text-decoration, text-align
 * Display: at least two of none, block, inline-black, inline
 * Sizing: height, width, max-width, min-width
 * Position: at least two of static, relative, fixed, absolute, sticky (apply these to position property)
 * Psuedo-class: :hover, :active

---
### Flexbox and Grid
Flexbox:
* apply flex to the display property.
* Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes

Grid:
* apply grid to the display property
* Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes

---
### CSS Selectors:
* Class Selector (.class)
* ID Selector (#id)
* Universal Selector (*)
* Element Selector (element) 
* Attribute Selector (e.g. [attribute=foo])     
* Pseudo-class Selector (e.g. p:hover)
* Selector List (element, element)                   /* select multiple elements */
* Combinators (you must use one of each)    /* specify selections based on element positioning in the DOM tree */
* Descendant Combinator (element element)
  * Child Combinator (element > element)
  * General sibling combinator (element ~ element)
  * Adjacent sibling combinator (element + element)
  * Combining Two Selectors (element.class)
* New Selectors /*Adopted in December 2023!*/
  * :has()  /*You must use this selector. Click [hereLinks to an external site.](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) for how to use. This is a new selector that was widely adopted in 2023.*/
  * Nested Selectors
      * Nested selectors are another type of selector that have recently been adopted in 2023. [HereLinks to an external site.](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) is some more information about this selector. Please also include at least one type of this selector in your CSS.
